default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { localhost } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_api_development

test:
  <<: *default
  database: ecommerce_api_test

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
